#23299 lambda to fn
D0nGiovanni/TypeScript pull request #12
Opened 2018-10-19 12:15 UTC by bigaru

2018-10-19 16:13 UTC, D0nGiovanni requested changes

2018-10-19 16:13 UTC, D0nGiovanni commented on src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
> +    function makeFunctionDeclaration(func: FunctionExpression | ArrowFunction, statement: VariableStatement, name: Identifier, body: Block) {
Changes:
- inline function. 

Reasoning:
- simple forwarding of values

2018-10-19 16:13 UTC, D0nGiovanni commented on src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
> +        const variableDeclarationList = findAncestor(variableDeclaration, n => isVariableDeclarationList(n))!;
Changes:
```suggestion
        const variableDeclarationList = variableDeclaration.parent;
```
Reasoning:
- simpler and more readable
- no double assertion

2018-10-19 16:13 UTC, D0nGiovanni commented on src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
> +        const statement = findAncestor(variableDeclaration, n => isVariableStatement(n))!;
Same as above.
```suggestion
        const statement = variableDeclarationList.parent;
```

2018-10-19 16:13 UTC, D0nGiovanni commented on src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
> +
No leading white line
```suggestion
```

2018-10-19 16:13 UTC, D0nGiovanni commented on src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
> +                body = makeBlock(func);
Changes: 
- extract to function, i.e. `getEditInfoForConvertToAnonymousFunction` 
  - directly return `RefactorEditInfo`, i.e. `return getToAnonFnEdits(...)`
- same for the other 2 cases

Reasoning:
- function is too long

2018-10-19 16:13 UTC, D0nGiovanni commented on src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
> +        let body: Block | ConciseBody;
Changes:
- move (going into extracted function)
- same goes for `newNode` and `edits`

Reasoning:
- duh!

2018-10-19 16:13 UTC, D0nGiovanni commented on src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
> +    function makeBlock(func: ArrowFunction | FunctionExpression): Block {
Changes:
- change name to `convertToBlock`
- change parameter to `body: ConciseBody`

Reasoning:
- clarify intention
- `func` not needed, only `func.body` ever used

2018-10-19 16:13 UTC, D0nGiovanni commented on src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
> +        name: Identifier;
Changes:
```suggestion
```
Reasoning:
- redundant, can get from `variableDeclaration`

2018-10-19 16:13 UTC, D0nGiovanni commented on src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
> +                    body = head.expression!;
Have you tested expression-less return? 
- like this: `return;`

Should probably also be a test case

2018-10-19 16:13 UTC, D0nGiovanni commented on src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
> +        return { renameFilename: undefined, renameLocation: undefined, edits };
```suggestion
        return undefined;
```
Reasoning:
- other cases returned above

2018-10-19 16:13 UTC, D0nGiovanni commented on src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
> +        if (!(isVariableDeclaration(parent) || (isVariableDeclarationList(parent) && parent.declarations.length === 1))) return undefined;
Changes:
- extract condition to `!isSingleVariableDeclaration(node: Node)`

Reasoning
- clarify intent, otherwise hard to read/understand

2018-10-19 16:13 UTC, D0nGiovanni commented on src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
> +        if (!variableDeclaration.initializer || !isArrowFunction(variableDeclaration.initializer)) return undefined;
Changes:
- extract variableDeclaration.initializer

2018-10-19 16:13 UTC, D0nGiovanni commented on src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
> +            const statements: Statement[] = [createReturn(func.body)];
inline `statements`?

2018-10-19 16:13 UTC, D0nGiovanni commented on src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
> +    function getArrowFunctionFromDeclaration(parent: Node): ArrowFunction | undefined {
Changes:
- rename to `getArrowFunctionFromVariableDeclaration`

Reasoning:
- clarify intent

2018-10-19 16:13 UTC, D0nGiovanni commented on src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
> +    interface BasicInfo {
Changes:
- rename to `FunctionInfo`

Reasoning:
- clarify intent

2018-10-19 16:13 UTC, D0nGiovanni commented on src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
> +    interface HeaderInfo {
Changes:
- rename to `VariableInfo`

Reasoning:
- clarify intent

2018-10-19 16:13 UTC, D0nGiovanni commented on src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
> +        fromDeclaration: boolean;
Changes:
- rename to `selectedVariableDeclaration`

Reasoning:
- clarify intent

2018-10-19 16:13 UTC, D0nGiovanni commented on src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
> +        const { fromDeclaration, func } = info;
- rename like above

2018-10-19 16:13 UTC, D0nGiovanni commented on src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
> +    function getInfo(file: SourceFile, startPosition: number): BasicInfo | undefined {
Changes:
- rename to `getFunctionInfo`

Reasoning:
- consistency, see return type

2018-10-19 16:13 UTC, D0nGiovanni commented on src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
> +    function getHeaderInfo(func: FunctionExpression | ArrowFunction): HeaderInfo | undefined {
Changes:
- rename to `getVariableInfo`

Reasoning:
- consistency, see return type

2018-10-19 16:13 UTC, D0nGiovanni commented on tests/cases/fourslash/refactorConvertArrowFunctionOrFunctionExpression_Availability_Anon.ts
> +verify.not.refactorAvailable("Convert arrow function or function expression", "Convert to arrow function");
no new line at end of file - change for all files

2018-10-19 16:13 UTC, D0nGiovanni commented on tests/cases/fourslash/refactorConvertArrowFunctionOrFunctionExpression_Availability_Anon_FnParam.ts
> +/// <reference path='fourslash.ts' />
- filename should be ...Argument.ts not Param
- filenames not consistent use ToAnon/ToArrow exclusively

2018-10-23 05:48 UTC, bigaru commented
It contains only the old review. Please go to new PR #13 .

2018-10-23 05:48 UTC, closed without merging